name: Release

## Commit prefixes and effects (https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format)

# build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
# ci: Changes to our CI configuration files and scripts (examples: CircleCi, SauceLabs)
# docs: Documentation only changes
# perf: A code change that improves performance
# test: Adding missing tests or correcting existing tests
# refactor: A code change that neither fixes a bug nor adds a feature
# feat: A new feature (triggers minor release)
# fix: A bug fix (triggers patch relase)
# BREAKING CHANGE: Breaking changes (triggers major release)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v3

      - name: '🔧 setup node'
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          cache: npm

      - name: '🔧 install npm@latest'
        run: npm i -g npm@latest

      - name: '📦 install dependencies'
        run: npm ci

      - name: '📊 repository visualizer'
        id: diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          excluded_paths: '.github,.vscode,node_modules,dist,build,'
          output_file: 'public/diagram.svg'
          should_push: false
          root_path: '/'

      - name: '📊 visualiser artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: diagram
          path: public/diagram.svg

      - name: '🚀 build app'
        run: npm run build

      - name: '📂 production artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/

  release:
    name: Semantic release
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.semantic-release.outputs.release-tag }}
    needs:
      - build
    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v3

      - name: '♻️ clean up artifact paths'
        run: |
          rm -rf public/diagram.svg
          rm -rf supabase/diagrams/

      - name: '📂 download build artifacts'
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/

      - name: '📂 download diagram artifacts'
        uses: actions/download-artifact@v2
        with:
          name: diagram
          path: public/

      - name: '🚀 semantic release'
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
          semantic_version: 15.13.28 # version range
        id: semantic # Need an `id` for output variables
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

<<<<<<< Updated upstream
      - name: '📊 package version'
        if: steps.semantic.outputs.new_release_published == 'true'
=======
      - name: '📦 package version'
        if: ${{ steps.semantic.outputs.new_release_published }}
>>>>>>> Stashed changes
        run: |
          git config user.name "Release Bot"
          git config user.email "release@github.com"

          git add package.json
          git commit -m "🐳 new version ${{ steps.semantic.outputs.new_release_version }}"
          git push origin main

          echo "🐳 new version released"
          echo ${{ steps.semantic.outputs.new_release_version }}
