name: Release new version

on:
  push:
    branches: [test-CI]
  pull_request:
    branches: [test-CI]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://nodejs.org/en/about/releases/
        node-version: 17.x
    steps:
      - uses: actions/checkout@v3

      # About Semantic Release: https://github.com/semantic-release/semantic-release#commit-message-format
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 15.13.28 # version range for semantic-release
          branch: test-CI
          env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog
      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
